/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.gui.eksport;

import javax.swing.JRadioButton;

public class WybierzEksportPanel extends javax.swing.JPanel {

    /**
     * Creates new form WybierzEksportPanel
     */
    public WybierzEksportPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        allStudents = new javax.swing.JRadioButton();
        allGroups = new javax.swing.JRadioButton();
        allSchemas = new javax.swing.JRadioButton();
        allSubjects = new javax.swing.JRadioButton();

        org.openide.awt.Mnemonics.setLocalizedText(allStudents, org.openide.util.NbBundle.getMessage(WybierzEksportPanel.class, "WybierzEksportPanel.allStudents.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(allGroups, org.openide.util.NbBundle.getMessage(WybierzEksportPanel.class, "WybierzEksportPanel.allGroups.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(allSchemas, org.openide.util.NbBundle.getMessage(WybierzEksportPanel.class, "WybierzEksportPanel.allSchemas.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(allSubjects, org.openide.util.NbBundle.getMessage(WybierzEksportPanel.class, "WybierzEksportPanel.allSubjects.text")); // NOI18N
        allSubjects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allSubjectsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(allStudents)
                    .addComponent(allGroups)
                    .addComponent(allSchemas)
                    .addComponent(allSubjects))
                .addContainerGap(259, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(allStudents)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(allGroups)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(allSubjects)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(allSchemas)
                .addContainerGap(192, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void allSubjectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allSubjectsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allSubjectsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton allGroups;
    private javax.swing.JRadioButton allSchemas;
    private javax.swing.JRadioButton allStudents;
    private javax.swing.JRadioButton allSubjects;
    // End of variables declaration//GEN-END:variables

    public boolean isAllGroups() {
        return allGroups.isSelected();
    }

    public boolean isAllSchemas() {
        return allSchemas.isSelected();
    }

    public boolean isAllStudents() {
        return allStudents.isSelected();
    }

    public boolean isallSubjects() {
        return allSubjects.isSelected();
    }

}
