/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.gui.przedmioty;

import org.database.models.GrupaOcen;
import org.database.models.Przedmiot;
import org.database.models.SEMESTR;
import org.database.models.TYP_OCENIANIA;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Mariushrek
 */
public class EdytujPrzedmiotPanel extends javax.swing.JPanel {
    private JButton OK_Button = new JButton("Dodaj do bazy");
    private JButton CANCEL_Button= new JButton("Anuluj");
    private Przedmiot przedmiot_edycja = null;
    
    /**
     * Creates new form EdytujPrzedmiot
     */
    
     public EdytujPrzedmiotPanel(Przedmiot przedmiot) {
        przedmiot_edycja = przedmiot;
        initComponents();
        nazwa_przedmiotu.setText(przedmiot_edycja.getNazwa());
        List<GrupaOcen> lista = GrupaOcen.getAllGrupaOcen(0);
        int i = 0; 
        for (GrupaOcen p : lista) {
            grupa_ocen.addItem(p);
            if(p.getNazwa().equals(przedmiot_edycja.getGrupaOcen().getNazwa())) grupa_ocen.setSelectedItem(p);
        }
        typ_oceniania.setSelectedItem(przedmiot_edycja.getTypOceniania());
        if(przedmiot_edycja.getSemestr() == SEMESTR.LETNI) {
            sem_zimowy.setSelected(false); sem_letni.setSelected(true);
        } else {
            sem_letni.setSelected(false); sem_zimowy.setSelected(true);
        }
        for(String s : UniversalFunctions.RokAkademicki()) {
            rok_akademicki.addItem(s);
            if(s.split("/")[0].equals(przedmiot_edycja.getRokAkademicki()+"")) rok_akademicki.setSelectedItem(s);
        }
        buttonGroup1.add(sem_letni);
        buttonGroup1.add(sem_zimowy);
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        typ_oceniania = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        sem_letni = new javax.swing.JRadioButton();
        rok_akademicki = new javax.swing.JComboBox();
        buttonGroup1 = new javax.swing.ButtonGroup();
        sem_zimowy = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        grupa_ocen = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        nazwa_przedmiotu = new javax.swing.JTextField();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(EdytujPrzedmiotPanel.class, "EdytujPrzedmiotPanel.jLabel3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jButton1, org.openide.util.NbBundle.getMessage(EdytujPrzedmiotPanel.class, "EdytujPrzedmiotPanel.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(EdytujPrzedmiotPanel.class, "EdytujPrzedmiotPanel.jLabel4.text")); // NOI18N

        typ_oceniania.setModel(new javax.swing.DefaultComboBoxModel(TYP_OCENIANIA.values()));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(EdytujPrzedmiotPanel.class, "EdytujPrzedmiotPanel.jLabel5.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(sem_letni, org.openide.util.NbBundle.getMessage(EdytujPrzedmiotPanel.class, "EdytujPrzedmiotPanel.sem_letni.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(sem_zimowy, org.openide.util.NbBundle.getMessage(EdytujPrzedmiotPanel.class, "EdytujPrzedmiotPanel.sem_zimowy.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(EdytujPrzedmiotPanel.class, "EdytujPrzedmiotPanel.jLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(EdytujPrzedmiotPanel.class, "EdytujPrzedmiotPanel.jLabel2.text")); // NOI18N

        nazwa_przedmiotu.setText(org.openide.util.NbBundle.getMessage(EdytujPrzedmiotPanel.class, "EdytujPrzedmiotPanel.nazwa_przedmiotu.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(nazwa_przedmiotu, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(grupa_ocen, javax.swing.GroupLayout.Alignment.LEADING, 0, 205, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(rok_akademicki, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(sem_zimowy, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(sem_letni, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                                .addComponent(typ_oceniania, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nazwa_przedmiotu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(grupa_ocen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(11, 11, 11)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(typ_oceniania, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sem_zimowy)
                    .addComponent(sem_letni))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rok_akademicki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        GrupaOcenDodajPanel panel = new GrupaOcenDodajPanel(OK_Button);
        OK_Button.setSelected(false); CANCEL_Button.setSelected(false);
        OK_Button.setEnabled(false);
        OK_Button.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Dobieramy sie do tego Jbuttona
                JButton btn = (JButton)e.getSource();
                // Przez dluga sciezke ojcow docieramy do JDialogu
                JDialog panel = (JDialog) btn.getParent().getParent().getParent().getParent().getParent().getParent();
                OK_Button.setSelected(true);
                panel.dispose();
            }
        });
        CANCEL_Button.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Dobieramy sie do tego Jbuttona
                JButton btn = (JButton)e.getSource();
                // Przez dluga sciezke ojcow docieramy do JDialogu
                JDialog panel = (JDialog) btn.getParent().getParent().getParent().getParent().getParent().getParent();
                CANCEL_Button.setSelected(true);
                panel.dispose();
            }
        });
        JButton[] objects = new JButton[]{OK_Button, CANCEL_Button};
        int zwrot = JOptionPane.showOptionDialog(this, panel, "Dodaj schemat oceniania", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE, null, objects, objects[0]);
        if(OK_Button.isSelected()) zwrot = 0;
        if(CANCEL_Button.isSelected()) zwrot = 1;
        if(zwrot == 0) {
            panel.SaveAll();
            grupa_ocen.setModel(new javax.swing.DefaultComboBoxModel(GrupaOcen.getAllGrupaOcen(0).toArray()));
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox grupa_ocen;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nazwa_przedmiotu;
    private javax.swing.JComboBox rok_akademicki;
    private javax.swing.JRadioButton sem_letni;
    private javax.swing.JRadioButton sem_zimowy;
    private javax.swing.JComboBox typ_oceniania;
    // End of variables declaration//GEN-END:variables

    public void SaveAll() {
        przedmiot_edycja.setNazwa(nazwa_przedmiotu.getText());
        przedmiot_edycja.setTypOceniania(TYP_OCENIANIA.valueOf(typ_oceniania.getSelectedItem().toString()));
        przedmiot_edycja.setGrupaOcen(((GrupaOcen) grupa_ocen.getSelectedItem()));
        przedmiot_edycja.setSemestr((sem_zimowy.isSelected()? SEMESTR.ZIMOWY : SEMESTR.LETNI));
        przedmiot_edycja.setRokAkademicki(Integer.parseInt(rok_akademicki.getSelectedItem().toString().split("/")[0]));
        Przedmiot.updatePrzedmiot(przedmiot_edycja);
    }
}
