package org.gui.grupy_cwiczeniowe;

import org.database.models.GrupaCwiczeniowa;
import org.database.models.GrupaStudent;
import org.database.models.Student;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

public class PodepnijStudentaPanel extends javax.swing.JPanel {

    private final GrupaCwiczeniowa grupaCwiczeniowa;

    private final List studenciGrupyList = new ArrayList();
    private final List pozostaliStudenciList = new ArrayList();

    private StudentsModel studenciGrupy;
    private StudentsModel pozostaliStudenci;

    /**
     * Creates new form PodepnijStudenta
     */
    public PodepnijStudentaPanel(GrupaCwiczeniowa grupaCwiczeniowa) {
        this.grupaCwiczeniowa = grupaCwiczeniowa;
        initStudentsLists();
        initStudentsModels();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListStudenciGrupy = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListPozostaliStudenci = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        odepnijButton = new javax.swing.JButton();
        podepnijButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jListStudenciGrupy.setModel(studenciGrupy);
        jScrollPane1.setViewportView(jListStudenciGrupy);

        jListPozostaliStudenci.setModel(pozostaliStudenci);
        jScrollPane2.setViewportView(jListPozostaliStudenci);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(PodepnijStudentaPanel.class, "PodepnijStudentaPanel.jLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(odepnijButton, org.openide.util.NbBundle.getMessage(PodepnijStudentaPanel.class, "PodepnijStudentaPanel.odepnijButton.text")); // NOI18N
        odepnijButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odepnijButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(podepnijButton, org.openide.util.NbBundle.getMessage(PodepnijStudentaPanel.class, "PodepnijStudentaPanel.podepnijButton.text")); // NOI18N
        podepnijButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                podepnijButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(PodepnijStudentaPanel.class, "PodepnijStudentaPanel.jLabel3.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(odepnijButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                .addComponent(podepnijButton)
                .addGap(66, 66, 66))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(podepnijButton)
                    .addComponent(odepnijButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void odepnijButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odepnijButtonActionPerformed
        int selectedIndex = jListStudenciGrupy.getSelectedIndex();
        if (selectedIndex == -1) {
            JOptionPane.showMessageDialog(this, "Nie wybranu studenta!", "Odpianie studenta - BŁĄD", JOptionPane.ERROR_MESSAGE);
        } else {
            Student s = (Student) jListStudenciGrupy.getModel().getElementAt(selectedIndex);
            GrupaStudent.delete(s, grupaCwiczeniowa);
            studenciGrupy.removeElement(s);
            pozostaliStudenci.addElement(s);
            repaintJlists();
        }
    }//GEN-LAST:event_odepnijButtonActionPerformed

    private void repaintJlists() {
        jListStudenciGrupy.updateUI();
        jListPozostaliStudenci.updateUI();
    }

    private void podepnijButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_podepnijButtonActionPerformed
        int selectedIndex = jListPozostaliStudenci.getSelectedIndex();
        if (selectedIndex == -1) {
            JOptionPane.showMessageDialog(this, "Nie wybranu studenta!", "Podpinanie studenta - BŁĄD", JOptionPane.ERROR_MESSAGE);
        } else {
            Student s = (Student) jListPozostaliStudenci.getModel().getElementAt(selectedIndex);
            GrupaStudent.add(s, grupaCwiczeniowa);
            studenciGrupy.addElement(s);
            pozostaliStudenci.removeElement(s);
            repaintJlists();
        }
    }//GEN-LAST:event_podepnijButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jListPozostaliStudenci;
    private javax.swing.JList jListStudenciGrupy;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton odepnijButton;
    private javax.swing.JButton podepnijButton;
    // End of variables declaration//GEN-END:variables

    private void initStudentsLists() {
        for (Student s : Student.getByGroup(grupaCwiczeniowa.getId())) {
            studenciGrupyList.add(s);
        }
        for (Student s : Student.getAllWithoutGroup(grupaCwiczeniowa.getId())) {
            pozostaliStudenciList.add(s);
        }
    }

    private void initStudentsModels() {
        studenciGrupy = new StudentsModel(studenciGrupyList);
        pozostaliStudenci = new StudentsModel(pozostaliStudenciList);
    }

}
